name: Auto Deploy to GitHub Packages

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'LICENSE.md'
      - 'README.md'
      - '*.md'
      - 'docs/**'
      - '.github/*.md'

permissions:
  contents: write
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'maven'

      - name: Set up Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Auto-increment patch version
        run: |
          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Current version: $CURRENT_VERSION"

          BASE_VERSION=$(echo $CURRENT_VERSION | cut -d. -f1,2)
          PATCH_VERSION=$(echo $CURRENT_VERSION | cut -d. -f3)
          NEW_PATCH=$((PATCH_VERSION + 1))
          NEW_VERSION="${BASE_VERSION}.${NEW_PATCH}"

          echo "New version: $NEW_VERSION"
          mvn versions:set -DnewVersion=$NEW_VERSION -DgenerateBackupPoms=false
          git commit -am "🔖 Auto bump version to $NEW_VERSION"
          git push

      - name: Deploy to GitHub Packages
        run: mvn deploy --batch-mode
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
