name: Auto Deploy to GitHub Packages

on:
  push:
    branches:
      - master

permissions:
  contents: write
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'maven'

      - name: Set up Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Bump version using GitHub Run Number
        run: |
          VERSION=1.0.${{ github.run_number }}
          echo "New version: $VERSION"
          mvn versions:set -DnewVersion=$VERSION -DgenerateBackupPoms=false
          git commit -am "🔖 Auto bump version to $VERSION"
          git push

      - name: Deploy to GitHub Packages
        run: mvn deploy --batch-mode
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
